apiVersion: apps/v1
kind: Deployment
metadata:
  name: sesam-statuspage-monitoring
spec:
  selector:
    matchLabels:
      app: sesam-statuspage-monitoring
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  replicas: 1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sesam-statuspage-monitoring # ENDRES PER APPLIKASJON
  template:
    metadata:
      labels:
        app: sesam-statuspage-monitoring # ENDRES PER APPLIKASJON
    spec:
      serviceAccountName: sesam-statuspage-monitoring # ENDRES PER APPLIKASJON
      imagePullSecrets:
      - name: containerregistryprodsecret
      containers:
      - name: sesam-statuspage-monitoring # ENDRES PER APPLIKASJON
        image: containerregistryprod.azurecr.io/sesam-statuspage-monitoring:imagetag
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "500m"
            memory: "750Mi"