apiVersion: apps/v1
kind: Deployment
metadata:
  name: sesam-statuspage-monitoring
spec:
  selector:
    matchLabels:
      app: sesam-statuspage-monitoring
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  replicas: 1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sesam-statuspage-monitoring # ENDRES PER APPLIKASJON
  template:
    metadata:
      labels:
        app: sesam-statuspage-monitoring # ENDRES PER APPLIKASJON
    spec:
      serviceAccountName: sesam-statuspage-monitoring # ENDRES PER APPLIKASJON
      imagePullSecrets:
      - name: containerregistryprodsecret
      containers:
      - name: sesam-statuspage-monitoring # ENDRES PER APPLIKASJON
        image: containerregistryprod.azurecr.io/sesam-statuspage-monitoring:imagetag
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "500m"
            memory: "750Mi"
        env:
          - name: COMPONENT_ID
            value: "7hkbjbyn8g5q"
          - name: PAGE_ID
            value: "p5k58vp9ll32"
          - name: RECIPIENTS
            value: "[\"gabriell.vig@sesam.io\", \"Feng.Luan@hafslund.no\", \"sesam.henvendelser@hafslund.no\", \"craig.seamons@sesam.io\", \"ole.dale@sesam.io\"]"
          - name: SESAM_API_URL
            value: "https://3c9170a1.sesam.cloud/api"
          - name: SMTP_HOST
            value: "smtp.office365.com:587"
          - name: SMTP_SENDER
            value: "SesamMailSender@hafslund.no"
          - name: SMTP_USERNAME
            value: "SesamMailSender@hafslund.no"

